### ISSUE TITLE
Is this method secure?

### ISSUE THREAD

**Issue by mttspear** [markroland/converge-api-php#1]
Sorry for my lack of knowledge I have been reading the user guides from Converge etc and just want to make sure I am using this API safely and correctly.  

In my example the user adds their credit card # and details on a form at my website **example.com**

This information is then sent via post to my site **example.com/payment**

I then format the API (using this library) with the form data that has just been submitted and send the request to Converge (server to server).  

Is this the correct process?  I'm unsure about Credit Cards hitting my server (even though nothing is saved).  Thank you for your time.

**Comment by markroland** [comment]
Yes, that's the correct process. Check out the examples folder for some sample scripts.

Even though nothing is saved on your web server, the information is technically sent to the server and as such, will require your server to be PCI compliant. The security required is mostly based on your server environment and less on the code in this library. If you look at the source for this package, you'll see that it uses PHP's curl library to issue a HTTP Post to the Converge server.

I hope that helps. Best of luck.
