### ISSUE TITLE
Chrome 75 causing duplicate transactions

### ISSUE THREAD

**Issue by yatahaze** [markroland/converge-api-php#7]
Hi a few years back I integrated your code into ours and now my memory is fuzzy on if I changed anything or just left it stock, but something crazy has happened here recently.

When Chrome hit version 75 here, _most_ of my API calls to converge are getting duplicated. I switched to Opera and Firefox, but just yesterday we noticed both Opera and Firefox updated to 75 and now we're getting duplicates there too.

When we call the API, we record our own reference in our MySQL DB. If there's a duplicate within 24 hours it is denied, but it hasn't prevented this Converge issue because it hits the API twice (a second apart).

Do you know where I should look in terms of debugging this?

**Comment by markroland** [comment]
Interesting. I'm not sure why the browser would come in to play here since this is backend PHP code that doesn't interact with the browser directly.

I would recommend checking your PHP logs for errors and go from there.

**Comment by yatahaze** [comment]
I technically solved this, it appears to only take affect when you use a form that has an onsubmit warning. I disabled that and no longer have any double requests.
